apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timekeeper
  annotations:
    external-dns.alpha.kubernetes.io/hostname: timekeeper.spidereye.io
spec:
  rules:
  - host: timekeeper.spidereye.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: timekeeper
            port:
              number: 8080
